version: "3"

services:
  fireplace:
    container_name: "fireplace"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        APP_NAME: "fireplace-server"
        APP_PATH: "./cmd/fireplace-server"
    ports:
      - "0.0.0.0:8999:8999"
    depends_on:
      - mongo
    env_file:
      - ./.env

  mongo:
    container_name: "mongo-fireplace"
    image: mongo:bionic
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  fireplaceviewer:
    container_name: "fireplace-viewer"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./cmd/fireplace-viewer/Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        APP_NAME: "fireplace-viewer"
        APP_PATH: "./cmd/fireplace-viewer"
    ports:
      - "0.0.0.0:8090:8090"
    depends_on:
      - fireplace
    env_file:
      - ./.env

  fireplacelogging:
    container_name: "fireplacelogging"
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        APP_NAME: "fireplacelogging"
        APP_PATH: "./cmd/fireplacelogging"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
      - ./cmd/fireplacelogging/.env

  postgres:
    container_name: "fireplacelogging-postgres"
    restart: unless-stopped
    image: "postgres:14-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  mongo:
  postgres:

